version: '3.9'
services:
  db:
    image: postgres:13.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./docker.env

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
    - .:/pizzaroder
    ports:
    - 8000:8000
    env_file:
      - ./docker.env
    depends_on:
      - db

volumes:
  postgres_data:
