# Generated by Django 3.2.2 on 2021-05-14 05:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], max_length=50)),
                ('flavor', models.CharField(choices=[('', 'Select a flavor'), ('MARGARITA', 'Margarita'), ('MARINARA', 'Marinara'), ('SALAMI', 'Salami')], max_length=30)),
                ('count', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('PRODUCTION', 'In Production'), ('DELIVERING', 'Left to Deliver'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=30)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.customer')),
            ],
        ),
    ]
