# Generated by Django 3.2.2 on 2021-05-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210514_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='flavor',
            field=models.CharField(choices=[(None, 'Select a flavor'), ('MARGARITA', 'Margarita'), ('MARINARA', 'Marinara'), ('SALAMI', 'Salami')], max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.CharField(choices=[(None, 'Select a size'), ('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], max_length=50),
        ),
    ]
